# Generated by Django 2.2.4 on 2019-10-04 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('enquirer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.Enquirer')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField()),
                ('enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.Enquiry')),
            ],
        ),
    ]
