# Generated by Django 2.2.4 on 2019-10-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(default='', max_length=20),
        ),
    ]
