# Generated by Django 2.2.4 on 2019-10-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_auto_20191008_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='phone',
        ),
        migrations.AddField(
            model_name='enquirer',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
    ]
