# Generated by Django 2.2.4 on 2020-03-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_couple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='enquirer',
        ),
        migrations.RemoveField(
            model_name='response',
            name='enquiry',
        ),
        migrations.DeleteModel(
            name='Enquirer',
        ),
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
